name: lando-tomcat-7
services:
  custom:
    type: tomcat:7
    ssl: true
    webroot: .
    build_as_root:
      - apt update -y
      - apt install -y curl

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/tomcat": ./../../
